image: registry.gitlab.com/chasingspace/lunar

variables:
  lua: "lua=5.1"

stages:
  - test
  - build

before_script:
  - LUA_PATH="$LUA_PATH;./lib/?.lua;./lib/?/init.lua" lua ./lib/lunar/lunarc/init.lua

busted:
  stage: test
  script:
    - luarocks install busted
      && luarocks install luacov
      && luarocks install luacheck
    - export LUA_PATH="$LUA_PATH;./?.lua;./?/init.lua"
    - luacheck ./dist -q --only 011
    - busted -C ./dist --verbose --coverage

build:
  stage: build
  script: cd ./build && chmod +x ./build.sh && ./build.sh
  artifacts:
    paths:
      - ./build/bin/lunarc
      - ./build/bin/lunarc.exe
    expire_in: 1 week