image: python

variables:
  lua: "lua=5.1"

stages:
  - test
  - build

before_script:
  - pip install hererocks
    && hererocks lua_install -r^ --$lua
  - export PATH=$PATH:$PWD/lua_install/bin
    && export LUA_PATH="$LUA_PATH;./?.lua;./?/init.lua"
  - luarocks install luafilesystem
  - LUA_PATH="$LUA_PATH;./lib/?.lua;./lib/?/init.lua" ./lua_install/bin/lua ./lib/lunar/lunarc/init.lua

busted:
  stage: test
  script:
    - luarocks install busted
      && luarocks install luacov
      && luarocks install luacheck
    - luacheck ./dist -q --only 011
    - busted -C ./dist --verbose --coverage
