language: python
sudo: required

env:
  - LUA="lua=5.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin
  - export LUA_PATH="./lib/?.lua;./lib/?/init.lua;$LUA_PATH;./?.lua;./?/init.lua"

install:
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls
  - lua ./lib/lunar/lunarc/init.lua
  - chmod +x ./install.sh
  - sudo ./install.sh

script:
  - lunarc
  - busted -C ./dist --verbose --coverage

after_success:
  - luacov-coveralls -r ./dist/lunar -e $TRAVIS_BUILD_DIR/dist/lua_install -e "_spec"
