dist: xenial
language: generic

addons:
  apt:
    packages:
    - lua5.1
    - luarocks
    - build-essential
    - gcc-multilib
    - mingw-w64

install:
- sudo luarocks install busted
- sudo luarocks install luacov
- sudo luarocks install luacheck
- sudo luarocks install luastatic
- export LUA_PATH="$LUA_PATH;./?.lua;./?/init.lua;";
- LUA_PATH="$LUA_PATH;./lib/?.lua;./lib/?/init.lua" lua ./lib/lunar/lunarc/init.lua

script:
- luacheck ./dist -q --only 011
- busted -C ./dist --verbose --coverage

before_deploy:
- cd ./build
- chmod +x ./build.sh
- "./build.sh"

deploy:
  skip_cleanup: true
  provider: releases
  draft: true
  api_key:
    secure: ovydp5PVXNmW5Z3Ao6eXP16p+qJi7rJMZkFcaoEhmKKyBFV57LPap/tosdRaD+jktehwYQakXNc5iB3oOcrtAk/4yWgC5oKlGdLyHpf2McLqHaK3WnCQhKWs5fovh2gz1XDeYU4G9ur7gQwVSmdiu3DcC1MHByXKr/MxrqizndyQZbUJq/2gipZxMcnRsbQeBrClsFPrXA9jX89zkA5h/eN2v/UjWeTxDaK8+6BZnCk94Oj7ojJ6YNsbRtSnMP+dr5yip9+G6tcKTJpX+o2Pil2M5uhEEVFQHq2UiZZOhsQGyH/JU0WpaJIUN2ysxxlm6ECOr4y0myKuxUG132w06iayG/hk+4Rda22EhJc87FxbIsFaZ7c598HgL2bFpaumye4BM/KJoadBiCtTmTdWjzgHgWai8606j5t5W7LJi1RZvzYW+pVapzkfNpAxY7mG7TJAgRIPz7vqhCbSdGZyhAeoty66cXbFun1hGq4FGx0/tqI27Ttdbo9lng9dS0giTpICeym0xk2vwIfGpa9zr2CZGlHvZiToACCl7Tj6EGOD69lX7/CEkXiX4vD+2IhLR1sO8KNAdWapHNVxdpIstZA/8kMomUlbnxKD1HHUB09e18057aPiDrTe5ou9cA5F+X/CrLw44EOXF60aFsHAqEIfcwMNNx2fXUVkAlvwtkg=
  file:
  - "./bin/lunarc"
  - "./bin/lunarc.exe"
  on:
    branch: master
    repo: lunarlang/lunar
